Repository EmoHiphopSeason2/mz2mo-client, pull requests merged in 2023-07, with the labels that each got.

#27 [MZO-39] Emoji-Picker 구현
  src/app/template.tsx
  src/components/EmojiPicker.tsx
  src/components/button/EmojiButton.tsx
  src/components/header/Header.tsx
  src/stores/emoji-picker/actions.ts
  src/stores/emoji-picker/index.ts
  src/stores/emoji-picker/stores.ts
  src/types/atom/emojiPicker.ts
  src/types/atom/index.ts
Labels: ✨ Feature

#31 [MZO-53] queryClient와 Hydration 을 병합한 컴포넌트 개발
  src/components/prefetch-hydration/PrefetchHydration.tsx
  src/components/prefetch-hydration/hydrateOnClient.tsx
  src/components/prefetch-hydration/index.ts
  src/utils/getQueryClient.tsx
Labels: 🔨 Refactor

#33 [MZO-40] 하단 플레이어 바 UI 구현
  global.d.ts
  package.json
  pnpm-lock.yaml
  postcss.config.js
  src/app/globals.css
  src/app/template.tsx
  src/assets/icons/playlist.svg
  src/components/bottom-player/BottomMusicPlayer.module.css
  src/components/bottom-player/BottomMusicPlayer.tsx
  src/components/bottom-player/index.ts
  src/components/youtube-player/index.ts
  src/stores/youtube-controller/actions.ts
  src/stores/youtube-controller/stores.ts
  src/utils/format.ts
  tailwind.config.js
Labels: ✨ Feature

#34 [MZO-48] toast 공용 모듈 및 UI 구현
  package.json
  pnpm-lock.yaml
  src/app/template.tsx
  src/assets/icons/alertError.svg
  src/assets/icons/alertInfo.svg
  src/assets/icons/alertSuccess.svg
  src/assets/icons/arrowLeft.svg
  src/assets/icons/arrowRight.svg
  src/assets/icons/check.svg
  src/assets/icons/chevronLeft.svg
  src/assets/icons/chevronRight.svg
  src/assets/icons/close.svg
  src/assets/icons/controlNext.svg
  src/assets/icons/controlPause.svg
  src/assets/icons/controlPlay.svg
  src/assets/icons/controlPrev.svg
  src/assets/icons/menu.svg
  src/assets/icons/plus.svg
  src/assets/icons/user.svg
  src/components/toast/Toast.tsx
  src/components/toast/ToastProvider.tsx
  src/components/toast/index.tsx
  src/stores/toast/actions.ts
  src/stores/toast/index.ts
  src/stores/toast/stores.ts
  src/types/atom/index.ts
  src/types/atom/toast.ts
Labels: ✨ Feature

#29 [MZO-38] 음악 재생 페이지 퍼블리싱 및 기능 구현
  src/app/layout.tsx
  src/app/playing/layout.tsx
  src/app/playing/page.tsx
  src/app/template.tsx
  src/assets/icons/loop.svg
  src/assets/icons/loopOnce.svg
  src/assets/icons/volume.svg
  src/assets/icons/volumeOff.svg
  src/components/app-portal/AppPortal.tsx
  src/domains/playing/emoji-list/EmojiVoteList.tsx
  src/domains/playing/emoji-list/index.ts
  src/domains/playing/play-controller/PlayController.module.css
  src/domains/playing/play-controller/PlayController.tsx
  src/domains/playing/play-controller/index.ts
  src/domains/playing/vinyl-record/VinylRecord.tsx
  src/domains/playing/vinyl-record/index.ts
  src/hooks/useToggle.ts
  src/stores/youtube-controller/actions.ts
  tailwind.config.js
  tsconfig.json
Labels: ✨ Feature

#35 [MZO-55] 모달 관련 이슈 해결
  src/app/playing/page.tsx
  src/app/template.tsx
  src/components/EmojiPicker.tsx
  src/domains/playing/vinyl-record/VinylRecord.tsx
Labels: 🐞 Bug

#37 [MZO-58] 에러 처리를 위한 ErrorBoundary 컴포넌트 도입
  package.json
  pnpm-lock.yaml
  src/components/async-boundary/AsyncBoundary.tsx
  src/components/async-boundary/index.ts
  src/components/error-boundary/ErrorBoundary.tsx
  src/components/error-boundary/index.ts
  src/components/prefetch-hydration/PrefetchHydration.tsx
  src/utils/ReactQueryProvider.tsx
Labels: ✨ Feature

#39 [MZO-57] Toast 관련 리팩토링
  src/app/playing/page.tsx
  src/hooks/useToast.ts
  src/stores/toast/actions.ts
Labels: 🔨 Refactor

#41 [MZO-60] 플레이리스트 마크업 작업
  next.config.js
  src/app/layout.tsx
  src/app/playing/layout.tsx
  src/app/playing/page.tsx
  src/app/template.tsx
  src/assets/icons/menu.svg
  src/assets/icons/playlist.svg
  src/assets/icons/playlistMenu.svg
  src/components/EmojiPicker.tsx
  src/components/app-portal/AppPortal.tsx
  src/components/bottom-player/BottomMusicPlayer.tsx
  src/components/header/MenuButton.tsx
  src/components/playlist/Playlist.tsx
  src/components/playlist/PlaylistButton.tsx
  src/components/playlist/hooks/index.ts
  src/components/playlist/hooks/usePlaylist.ts
  src/components/playlist/index.ts
  src/components/playlist/store/actions.ts
  src/components/playlist/store/index.ts
  src/components/playlist/store/stores.ts
  tailwind.config.js
Labels: ✨ Feature
