Repository EmoHiphopSeason2/mz2mo-client, pull requests merged in 2023-06, with the labels that each got.

#1 feat: 프로젝트 기초 세팅
  .eslintignore
  .eslintrc
  .eslintrc.json
  .github/pull_request_template.md
  .prettierrc
  README.md
  global.d.ts
  next.config.js
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/utils/validation.ts
  tsconfig.json
Labels: ✨ Feature

#4 [MZO-8] Github Action CI/CD Pipeline 구축
  .github/CODEOWNERS
  .github/workflows/development.yml
  .github/workflows/production.yml
  .prettierrc
  appspec.yml
  deploy.sh
  package.json
  src/app/layout.tsx
  src/app/page.tsx
Labels: ⚙ Setting

#5 [MZO-34] API 모듈 및 인터페이스 구축
  package.json
  pnpm-lock.yaml
  src/apis/API.ts
  src/app/ReactQueryProvider.tsx
  src/utils/getQueryClient.tsx
  src/utils/hydrateOnClient.tsx
Labels: ✨ Feature, ⚙ Setting

#10 [MZO-35] Prettier plugin 추가 설치
  .prettierrc
  package.json
  pnpm-lock.yaml
  src/app/ReactQueryProvider.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/utils/getQueryClient.tsx
  src/utils/hydrateOnClient.tsx
Labels: ⚙ Setting

#12 [MZO-30] Next-PWA 및 manifest 설정
  .gitignore
  next.config.js
  package.json
  pnpm-lock.yaml
  public/icon-192x192.png
  public/icon-256x256.png
  public/icon-384x384.png
  public/icon-512x512.png
  public/manifest.json
  src/app/layout.tsx
  src/constants/siteMetaData.ts
  src/worker/index.ts
  tsconfig.json
Labels: ✨ Feature, ⚙ Setting

#15 [MZO-33] 디자인 시스템 설정 (font, color)
  src/app/fonts.ts
  src/app/globals.css
  src/app/layout.tsx
  src/assets/fonts/Pretendard-Black.subset.woff2
  src/assets/fonts/Pretendard-Bold.subset.woff2
  src/assets/fonts/Pretendard-ExtraBold.subset.woff2
  src/assets/fonts/Pretendard-ExtraLight.subset.woff2
  src/assets/fonts/Pretendard-Light.subset.woff2
  src/assets/fonts/Pretendard-Medium.subset.woff2
  src/assets/fonts/Pretendard-Regular.subset.woff2
  src/assets/fonts/Pretendard-SemiBold.subset.woff2
  src/assets/fonts/Pretendard-Thin.subset.woff2
  src/assets/icons/arrowLeft.svg
  src/assets/icons/arrowRight.svg
  src/assets/icons/check.svg
  src/assets/icons/chevronLeft.svg
  src/assets/icons/chevronRight.svg
  src/assets/icons/close.svg
  src/assets/icons/controlNext.svg
  src/assets/icons/controlPause.svg
  src/assets/icons/controlPlay.svg
  src/assets/icons/controlPrev.svg
  src/assets/icons/plus.svg
  src/assets/icons/user.svg
  tailwind.config.js
Labels: ✨ Feature, ⚙ Setting

#17 [MZO-43] 디자인 시스템 설정 (button components)
  global.d.ts
  next.config.js
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/assets/icons/arrowLeft.svg
  src/assets/icons/arrowRight.svg
  src/assets/icons/check.svg
  src/assets/icons/chevronLeft.svg
  src/assets/icons/chevronRight.svg
  src/assets/icons/close.svg
  src/assets/icons/controlNext.svg
  src/assets/icons/controlPause.svg
  src/assets/icons/controlPlay.svg
  src/assets/icons/controlPrev.svg
  src/assets/icons/plus.svg
  src/assets/icons/user.svg
  src/components/button/ArrowButton.tsx
  src/components/button/BasicButton.tsx
  src/components/button/EmojiButton.tsx
  src/components/button/LongButton.tsx
  tsconfig.json
Labels: ✨ Feature, ⚙ Setting

#19 [MZO-45] 디자인 시스템 설정 (header)
  src/assets/icons/arrowLeft.svg
  src/assets/icons/arrowRight.svg
  src/assets/icons/check.svg
  src/assets/icons/chevronLeft.svg
  src/assets/icons/chevronRight.svg
  src/assets/icons/close.svg
  src/assets/icons/controlNext.svg
  src/assets/icons/controlPause.svg
  src/assets/icons/controlPlay.svg
  src/assets/icons/controlPrev.svg
  src/assets/icons/menu.svg
  src/assets/icons/plus.svg
  src/assets/icons/user.svg
  src/components/header/Header.tsx
  src/components/header/LogoButton.tsx
  src/components/header/MenuButton.tsx
  src/components/header/PreviousButton.tsx
  src/components/header/Title.tsx
Labels: ✨ Feature
